const collageData=[
    {
        "university": "iit kanpur",
        "college": "iit kanpur",
        "college_type": "Affiliated College",
        "state": "kanpur",
        "district": "Prakasam",
        "url":"https://bsmedia.business-standard.com/_media/bs/img/article/2018-04/19/full/1524113491-1118.jpg",
        "rating":"4.5",
        "placement-percentage":"80%",
        "naacA":"Approved",
        "semester-fee":"80000",
        "count_of_10_lpa_package":"20 out of 100",
        "Area":"50 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "iit Bombay",
        "college": "iit Bombay",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "url":"https://alumni.acr.iitb.ac.in/wp-content/uploads/2023/07/1903x789_MB-1.jpg",
        "rating":"4.0",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "IIt Delhi",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://img.etimg.com/thumb/width-1200,height-900,imgsize-1248409,resizemode-75,msid-73880846/prime/technology-and-startups/the-iit-delhi-connection-of-indias-unicorns-and-what-it-means-for-innovation.jpg",
        "placement-percentage":"60%",
        "naacA":"Approved",
        "semester-fee":"70000",
        "count_of_10_lpa_package":"10 out of 100",
        "Area":"90 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+",
        "rating":"4.5",
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "iit kharagpur",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "url":"https://assets.thehansindia.com/h-upload/feeds/2019/07/10/194544-9.jpg",
        "placement-percentage":"80%",
        "naacA":"Approved",
        "semester-fee":"1200000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"90 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+",
        "rating":"4.5",
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "iit guhati",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "url":"https://www.iitg.ac.in/acad/slider_images/2.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+",
        "rating":"4.5",
    },
    {
        "university": "Chitkara University",
        "college": "Chitkara University",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://www.chitkara.edu.in/blogs/wp-content/uploads/2022/03/CUB4-Top-10-reasons-why-Chitkara-University-is-the-best-University-in-North-India.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+",
        "rating":"4.5",
        // "url":"https://www.chitkara.edu.in/blogs/wp-content/uploads/2022/03/CUB4-Top-10-reasons-why-Chitkara-University-is-the-best-University-in-North-India.jpg"
    },
    {
        "university": "ChandiGarh University",
        "college": "ChandiGarh University",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://dekhocampus.com/upload/180523090548chandigarh-university-global-education-summit-theme-global-acad_MYF4IZ2.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Lovely Professional University",
        "college": "Lovely Professional University",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://img.collegepravesh.com/2023/02/LPU-Jalandhar.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "GalGotia University",
        "college": "GalGotia University",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://dekhocampus.com/upload/0706230445432q5baqld.dib.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "DTU",
        "college": "Dtu University",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "Adarsa Degree College for Women (Id: C-32733)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "A.G.K.M.College (Id: C-32664)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "A.L.College of Education (Id: C-32711)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "Ali College of Education (Id: C-39243)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "AL Momin College of Education (Id: C-39261)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "Alpha College of Education (Id: C-39238)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "Alpha College of Education, Kanigiri (Id: C-44489)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "Alpha Degree College (Id: C-32797)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Prakasam",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    {
        "university": "Acharya Nagarjuna University, Guntur (Id: U-0003)",
        "college": "Aman Showkath B.Ed College (Id: C-39227)",
        "college_type": "Affiliated College",
        "state": "Andhra Pradesh",
        "district": "Guntur",
        "url":"https://upload.wikimedia.org/wikipedia/commons/d/d5/DelhiCollegeOfEngineering_BawanaCampus.jpg",
        "placement-percentage":"70%",
        "naacA":"Approved",
        "semester-fee":"100000",
        "count_of_10_lpa_package":"40 out of 100",
        "Area":"80 Acre",
        "Infrastucturequality":"A+",
        "lab_faculity":"A+"
    },
    
]
export {collageData};